---
resources:
  - ./elastic
  - ./kibana
  - ./filebeat-syslog
  - ./filebeat-netflow
  - ./beatload
  - ./logstash

configurations:
  - config.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: filebeat-syslog-ds
      spec:
        template:
          spec:
            containers:
              - name: filebeat-syslog
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kibana-dp
      spec:
        template:
          spec:
            containers:
              - name: kibana
                env:
                  - name: ELASTICSEARCH_HOSTS
                    value: "[\"https://$(ELASTIC_SVC):9200\"]"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: logstash-dp
      spec:
        template:
          spec:
            containers:
              - name: logstash
                env:
                  - name: ELASTIC_URI
                    value: "https://$(ELASTIC_SVC):9200"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: logstash-dp
      spec:
        template:
          spec:
            containers:
              - name: logstash
                env:
                  - name: XPACK_MONITORING_ELASTICSEARCH_HOSTS
                    value: "[\"https://$(ELASTIC_SVC):9200\"]"
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: filebeat-syslog-ds
      spec:
        template:
          spec:
            initContainers:
              - name: filebeat-syslog-setup
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: filebeat-syslog-ds
      spec:
        template:
          spec:
            containers:
              - name: filebeat-syslog
                env:
                  - name: LOGSTASH_HOST
                    value: "$(LOGSTASH_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: conn-check
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: ilm-setup
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: conn-check
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: filebeat-load
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: filebeat-load
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: filebeat-load-dashboard
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: filebeat-load-dashboard
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: auditbeat-load
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: auditbeat-load
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: auditbeat-load-dashboard
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: auditbeat-load-dashboard
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: metricbeat-load
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: metricbeat-load
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: metricbeat-load-dashboard
                env:
                  - name: KIBANA_HOST
                    value: "$(KIBANA_SVC)"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beatload-dp
      spec:
        template:
          spec:
            initContainers:
              - name: metricbeat-load-dashboard
                env:
                  - name: ELASTIC_HOST
                    value: "$(ELASTIC_SVC)"
