---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-netflow-ds
  labels:
    component: filebeat-netflow
spec:
  selector:
    matchLabels:
      component: filebeat-netflow
  template:
    metadata:
      labels:
        component: filebeat-netflow
    spec:
      volumes:
        - name: elastic-ca-cert
          secret:
            secretName: elastic-ca-cert
        - name: filebeat-netflow-config
          configMap:
            name: filebeat-netflow-config
      initContainers:
        - name: wait
          image: archmachina/elasticwait:0.1.3
          env:
            - name: CERT_VERIFY
              value: "0"
            - name: TIME_WAIT
              value: "30"
            - name: MAX_ATTEMPTS
              value: "60"
            - name: ELASTIC_HOST
              value: "elastic-svc"
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: localadmin_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: localadmin_password
      containers:
        - name: filebeat-netflow
          image: docker.elastic.co/beats/filebeat:8.5.3-amd64
          volumeMounts:
            - name: filebeat-netflow-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: filebeat-netflow-config
              mountPath: /usr/share/filebeat/ilm-policy.json
              subPath: ilm-policy.json
            - name: elastic-ca-cert
              mountPath: /usr/share/filebeat/certs/
          env:
            - name: ELASTIC_HOST
              value: "elastic-svc"
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: filebeat_username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: filebeat_password
          ports:
            - name: "udp-2055"
              protocol: UDP
              containerPort: 2055
              hostPort: 2055
